info:
  app:
    name: ${spring.application.name}
    profiles: ${spring.profiles.active}
    server:
      port: ${server.port}

server:
  port: 8088
  servlet:
    context-path: / #设置应用的目录.  前缀需要带/, 无需设置后缀, 示例 【 /xxx 】 or 【 / 】

spring:
  application:
    name: facade-http-edi-demo


currencyapi:
  host: https://api.currencyapi.com
  apiUrl: https://api.currencyapi.com/v3/latest
  apiKey: cur_live_eESOh2PndNo9M9rCZlO9RunTqlfUVcf8AHU27igu

misttrack:
  host: https://openapi.misttrack.io
  apiUrl: https://openapi.misttrack.io/v1/risk_score
  apiKey: pFKTDGgsOmalXdWMAr38Iox5HQYJUL9P

payout:
  host: https://x1.admin2millliet.com
  accessSecret: RS6t5Cqm4JjsrqeLya6xAsecx7RHD5e6